# Generated by Django 5.0.2 on 2024-03-07 14:45

import django.db.models.deletion
import django.utils.timezone
import mysite.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=mysite.models.VerificationCode.get_random_number, max_length=5)),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiryDate', models.DateTimeField(blank=True, default=mysite.models.VerificationCode.get_expiry_time, help_text='Expires in 10 min by default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
