# Generated by Django 4.1.7 on 2024-03-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_taskss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
