# Generated by Django 4.1.7 on 2024-03-20 14:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0004_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taskss',
            new_name='Task',
        ),
    ]
